name: ecommerce_with_bloc
description: "The project deals with Bloc learning path where freezed will be use for modeling and will try to maintain clean architecture."

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  retrofit: ^4.4.2
  get_storage: ^2.1.1
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  auto_route_generator: ^9.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
